# Generated by Django 4.1.5 on 2023-02-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_purchases_unique_together'),
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together={('group_id', 'user_id')},
        ),
    ]
