# Generated by Django 4.1.5 on 2023-02-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_item_purchases'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchases',
            unique_together={('user_id', 'item_id')},
        ),
    ]
