# Generated by Django 4.1.5 on 2023-02-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_appuser_item_purchased_by_delete_purchases'),
        ('home', '0006_group_group_members_alter_group_group_leader_and_more'),
        ('game', '0005_alter_game_keeper_id_delete_completions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
